import type { EvidenceItem, RepoRef } from './types'

export const demoRepo: RepoRef = {
  owner: 'silent-labs',
  repo: 'atlas',
  url: 'https://github.com/silent-labs/atlas',
}

export const demoEvidence: EvidenceItem[] = [
  {
    id: 'review-741',
    kind: 'review',
    actor: 'mira-chen',
    title: 'Requested tighter cache invalidation before merge',
    url: 'https://github.com/silent-labs/atlas/pull/741#pullrequestreview-1',
    createdAt: '2026-05-24T16:20:00Z',
    targetNumber: 741,
    body: 'Caught stale data path and asked for an integration check.',
    files: ['src/cache/revalidate.ts', 'tests/cache-revalidate.spec.ts'],
  },
  {
    id: 'review-739',
    kind: 'review',
    actor: 'mira-chen',
    title: 'Approved auth boundary after follow-up changes',
    url: 'https://github.com/silent-labs/atlas/pull/739#pullrequestreview-2',
    createdAt: '2026-05-22T13:04:00Z',
    targetNumber: 739,
    files: ['src/auth/session.ts', 'tests/session.spec.ts'],
  },
  {
    id: 'issue-728',
    kind: 'issue',
    actor: 'mira-chen',
    title: 'Reproduced intermittent import failure on Firefox',
    url: 'https://github.com/silent-labs/atlas/issues/728',
    createdAt: '2026-05-20T10:12:00Z',
    body: 'Added reproduction steps, environment notes, and failing trace.',
  },
  {
    id: 'commit-a91',
    kind: 'commit',
    actor: 'mira-chen',
    title: 'Add regression coverage for cache refresh race',
    url: 'https://github.com/silent-labs/atlas/commit/a91',
    createdAt: '2026-05-19T18:44:00Z',
    files: ['tests/cache-revalidate.spec.ts'],
    additions: 42,
    deletions: 3,
  },
  {
    id: 'merge-741',
    kind: 'merge',
    actor: 'niko-ray',
    title: 'Merged import queue stabilization',
    url: 'https://github.com/silent-labs/atlas/pull/741',
    createdAt: '2026-05-25T09:15:00Z',
    targetNumber: 741,
  },
  {
    id: 'issue-714',
    kind: 'issue',
    actor: 'niko-ray',
    title: 'Triaged duplicate API timeout reports into one owner thread',
    url: 'https://github.com/silent-labs/atlas/issues/714',
    createdAt: '2026-05-13T11:08:00Z',
  },
  {
    id: 'review-709',
    kind: 'review',
    actor: 'niko-ray',
    title: 'Blocked release note mismatch before 2.8.0',
    url: 'https://github.com/silent-labs/atlas/pull/709#pullrequestreview-3',
    createdAt: '2026-05-10T15:31:00Z',
    files: ['docs/releases/2.8.0.md'],
  },
  {
    id: 'commit-d21',
    kind: 'commit',
    actor: 'sana-builds',
    title: 'Clarify plugin setup guide and CLI examples',
    url: 'https://github.com/silent-labs/atlas/commit/d21',
    createdAt: '2026-05-18T14:25:00Z',
    files: ['docs/plugins/setup.md', 'README.md'],
    additions: 86,
    deletions: 22,
  },
  {
    id: 'commit-d22',
    kind: 'commit',
    actor: 'sana-builds',
    title: 'Document local fixture workflow',
    url: 'https://github.com/silent-labs/atlas/commit/d22',
    createdAt: '2026-05-16T08:45:00Z',
    files: ['docs/testing/fixtures.md'],
    additions: 54,
    deletions: 4,
  },
  {
    id: 'pr-692',
    kind: 'pull_request',
    actor: 'sana-builds',
    title: 'Improve contributor guide for first-run setup',
    url: 'https://github.com/silent-labs/atlas/pull/692',
    createdAt: '2026-05-07T17:10:00Z',
    state: 'merged',
    files: ['CONTRIBUTING.md', 'docs/getting-started.md'],
  },
  {
    id: 'review-696',
    kind: 'review',
    actor: 'ori-stack',
    title: 'Spotted migration ordering risk',
    url: 'https://github.com/silent-labs/atlas/pull/696#pullrequestreview-4',
    createdAt: '2026-05-05T12:40:00Z',
    files: ['src/db/migrations/028_add_index.sql'],
  },
]
